name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_TEST_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_TEST_SA_KEY }}
        export_default_credentials: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Check style with YAPF
      run: |
        python tools/style_check.py --path=flatland
    - name: Test with pytest
      run: |
        FLATLAND_REQUESTER_PAYS_PROJECT_ID=${{ secrets.GCP_TEST_PROJECT_ID }} FLATLAND_TEST_BUCKET=${{ secrets.FLATLAND_TEST_BUCKET }} pytest flatland
    - name: Test notebooks
      run: |
        python tools/notebook_tester.py --path=nb/structure-solver.ipynb
        python tools/notebook_tester.py --path=nb/data-generation.ipynb

